mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vote.urls')),
]

vote/urls.py
from django.urls import path


from .views import *

app_name = 'vote'

urlpatterns = [
    path('', index, name='index'),
    path('<str:pk>/', detail, name='detail'),
    path('<str:pk>/result/', result, name='result'),
    path('<str:pk>/vote/', vote, name='vote'),
]

vote/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class QuestionModel(models.Model):
    question_title = models.CharField(max_length=200)
    published = models.DateTimeField('date published')
    voted = models.ManyToManyField(
        User, default=None, blank=True, related_name='voted')

    def __str__(self) -> str:
        return self.question_title


class ChoiceModel(models.Model):
    question = models.ForeignKey(QuestionModel, on_delete=models.CASCADE)
    choice_title = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self) -> str:
        return self.choice_title

vote/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
from .models import *


# show last 5 vote
def index(request):
    user = request.user
    question_list = QuestionModel.objects.order_by('-published')[:5]
    context = {
        'question_list': question_list,
        'user': user,
    }
    return render(request, 'vote/index.html', context)


# show detail vote
def detail(request, pk):
    user = request.user
    question = get_object_or_404(QuestionModel, pk=pk)
    context = {
        'question': question,
        'user': user
    }
    print(user)
    print(question.choicemodel_set.all())
    return render(request, 'vote/detail.html', context)


# result
def result(request, pk):
    question = get_object_or_404(QuestionModel, pk=pk)
    context = {
        'question': question,
    }
    return render(request, 'vote/result.html', context)


# vote
def vote(request, pk):
    user = request.user
    if request.method == 'POST':

        question = get_object_or_404(QuestionModel, pk=pk)
        if user in question.voted.all():
            question.voted.remove(user)
        else:
            question.voted.add(user)
        try:
            voted_choice = question.choicemodel_set.get(
                pk=request.POST['choice'])
        except (KeyError, ChoiceModel.DoesNotExist):
            # Redisplay the question voting form.
            return render(request, 'polls/detail.html', {
                'question': question,
            })
        else:
            voted_choice.votes += 1
            voted_choice.save()
            return HttpResponseRedirect(reverse('vote:result', args=(question.id,)))

templates/main_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
          
        {% endblock title %}
    </title>

    {% include "snippets/style.html" %}

    {% block early_script %}
      
    {% endblock early_script %}
</head>
<body>
    
    <div class="container">
    {% include "snippets/navbar.html" %}
    {% block content %}
      
    {% endblock content %}
    </div>

    {% include "snippets/script.html" %}

    {% block end_script %}
      
    {% endblock end_script %}
</body>
</html>

templates/snippets/navbar.html
<nav class="navbar navbar-light bg-light">
	<a class="navbar-brand" href="#">Vote</a>
</nav>

templates/snippets/script.html
{% load static %}

<script src="{% static 'vendor/jquery/jquery.js' %}" type="text/javascript"></script>
<script src="{% static 'vendor/popper/popper.js' %}" type="text/javascript"></script>
<script src="{% static 'vendor/bootstrap/bootstrap.js' %}" type="text/javascript"></script>

templates/snippets/style.html
{% load static %}

<link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.css' %}">

vote/templates/vote/detail.html
{% extends "main_layout.html" %}

{% block title %}
    detail
{% endblock title %}

{% block content %}
    <h3 class="text-center mb-5 mt-3">Detail Vote</h3>
    <h4 class="text-center m-4">{{ question.question_title }}</h4>

    
    {% if user not in question.voted.all %}
    
        <form action="{% url 'vote:vote' question.id %}" method="POST">
            {% csrf_token %}
            
            {% for choice in question.choicemodel_set.all %}
            <div class="form-check">
                <input
                    type="radio"
                    name="choice"
                    class="form-check-input"
                    id="choice{{ forloop.counter }}"
                    value="{{ choice.id }}"
                />
                <label for="choice{{ forloop.counter }}">{{ choice.choice_title }}</label
                >
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-dark">Submit</button>
        </form>
            
    {% else %}
    
        <h3 class="text-center badge-danger">You have voted</h3>

    {% endif %}
        

    <a href="{% url 'vote:index' %}" class="btn btn-outline-dark">Back</a>
{% endblock content %}

vote/templates/vote/index.html
{% extends "main_layout.html" %}

{% block title %}
  vote
{% endblock title %}

{% block content %}
  <h3 class="text-center mb-4">Vote Question</h3>
  
  {% if question_list %}
    
    {% for question in question_list %}
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title">{{ question.question_title }}</h5>
          <a href="{% url 'vote:detail' question.id %}" class="btn btn-outline-warning">Vote</a>
          <a href="{% url 'vote:result' question.id %}" class="btn btn-outline-success">Result</a>
        </div>
      </div>
    {% endfor %}
      
  {% else %}
    <h4 class="text-center">cilukba ga ada vote</h4>
  {% endif %}

    
{% endblock content %}

vote/templates/vote/result.html
{% extends "main_layout.html" %}


{% block title %}
    result
{% endblock title %}

{% block content %}
    <h1 class="mb-5 text-center">{{ question.question_title }}</h1>

    <ul class="list-group mb-5">
	{% for choice in question.choicemodel_set.all %}
	    <li class="list-group-item">
		    {{ choice.choice_title }}  <span class="badge badge-dark float-right">{{ choice.votes }} vote{{ choice.votes | pluralize }}</span>
	    </li>
	{% endfor %}
    </ul>

    <a class="btn btn-secondary" href="{% url 'vote:index' %}">Back To Polls</a>
    <a class="btn btn-dark" href="{% url 'vote:detail' question.id %}">Vote again?</a>
{% endblock content %}